// ===============================
// CAMINHOS DAS IMAGENS
// ===============================
// Se trocar o nome de uma imagem na pasta "images",
// troque o caminho aqui tambem.

const imagens = {
  alemanha: "images/alemanha.png",
  aviao: "images/avião.png",
  bandeiraBrusque: "images/bandeira-brusque.png",
  bandeiraParana: "images/bandeira-parana.png",
  bandeiraRiojaneiro: "images/bandeira-riojaneiro.png",
  bandeiraRoraima: "images/bandeira-roraima.png",
  bandeiraSc: "images/bandeira-sc.png",
  brusquense: "images/brusquense.png",
  cachorro: "images/cachorro.png",
  capivara: "images/capivara.png",
  carnaval: "images/carnaval.png",
  carro: "images/carro.png",
  cuca: "images/cuca.png",
  elefante: "images/elefante.png",
  escultura: "images/estatua.png",
  fenarreco: "images/fenarreco.png",
  festaUva: "images/festa-uva.png",
  girafa: "images/girafa.png",
  hamburguer: "images/hamburguer.png",
  italia: "images/italia.png",
  leao: "images/leao.png",
  macaco: "images/macaco.png",
  marreco: "images/marreco.png",
  mascote: "images/mascote.png",
  mineiro: "images/mineiro.png",
  paranaense: "images/paranaense.png",
  pizza: "images/pizza.png",
  ponte: "images/ponte.png",
  ponteBambu: "images/ponte-bambu.png",
  ponteCorda: "images/ponte-corda.png",
  portugal: "images/portugal.png",
  roupas: "images/roupas.png",
  textil: "images/textil.png",
  zoo: "images/zoo.png",
  prefeitura: "images/pref.png",
  pirulito: "images/pirulito.png",
  brusque_fc: "images/brusque_fc.png",
  atletico_mineiro: "images/atletico_mineiro.png",
  fortaleza: "images/fortaleza.png",
  burrito: "images/burrito.png",
  amendoim: "images/amendoim.png",
  borracha: "images/borracha.png",
  bolo: "images/bolo.png",
  rioItajaimirim: "images/rio-itajaimirim.png",
  serra: "images/serra.jpeg",
  lagoa: "images/lagoa.jpeg",
  hipopotamo: "images/hipopotamo.png",
  redentor: "images/redentor.jpeg",
  eiffel: "images/eiffel.jpeg",
  espanha: "images/espanha.png",
  niteroi: "images/niteroi.png",
  ayrton_senna: "images/ponte_ayrton_senna.png",
  nilo: "images/nilo.png",
  pecuraria: "images/pecuaria.jpeg",
  agricultura: "images/agricultura.png"
};
